# zhangkaiyuan@wind-mobi.com 20170919 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
obj-y += ili9881c_hd720_dsi_vdo_hs.o

# zhangkaiyuan@wind-mobi.com 20170919 end



