#modified liukangping@wind-mobi.com 201500824 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += hx8399_fhd_dsi_vdo_hlt.o
#modified liukangping@wind-mobi.com 201500824 end



