##hebiao@wind-mobi.com add at 20161111 begin
# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft3427/include/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/wind_device_info/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft3427/include/firmware1/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/base

obj-y	+=  focaltech_ctl.o
obj-y	+=  focaltech_ex_fun.o
obj-y	+=  focaltech_flash.o
obj-y	+=  focaltech_Gesture.o
obj-y	+=  focaltech_core.o
obj-y	+=	focaltech_esd_protection.o
obj-y   +=  ft_gesture_lib.a
##hebiao@wind-mobi.com add at 20161111 end



