#
# Makefile for all kinds of Fingerprint
#
obj-$(CONFIG_FPSENSOR_FINGERPRINT) += fpsensor/

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
##liukangping 20170112 begin	
obj-$(CONFIG_SUNWAVE_FINGERPRINT)+= sunwave_fp/
##liukangping 20170112 begin	
##add by microarray 20170912 begin	
obj-$(CONFIG_MICROARRAY_FINGERPRINT)+= microarray_fp/
##add by microarray 20170912 begin
	