# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the touchscreen drivers.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_AW_INPUT_CTP)    += gslx680new/
obj-$(CONFIG_AW_INPUT_CTP)    += wacom_pen/
obj-$(CONFIG_AW_INPUT_CTP)    += gt9xxnew/
