# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/msg2836/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/gt9xx_mtk/include/$(CONFIG_GTP_CONFIG)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
# add by qiangang@wind-mobi.com 20170728 begin
ccflags-y += -I$(srctree)/drivers/misc/mediatek/wind_device_info/
# add by qiangang@wind-mobi.com 20170728 end
obj-y	+=  ilitek_drv_hotknot.o
obj-y	+=  ilitek_drv_hotknot_queue.o
obj-y	+=  ilitek_drv_iliproc.o
obj-y	+=  ilitek_drv_main.o
obj-y	+=  ilitek_drv_mp_test.o
obj-y	+=  ilitek_drv_mtk.o
#obj-y	+=  ilitek_drv_qcom.o
#obj-y	+=  ilitek_drv_sprd.o
obj-y	+=  ilitek_drv_update.o


