snd-soc-tfa98xx-objs := tfa98xx.o
snd-soc-tfa98xx-objs += tfa_container.o
snd-soc-tfa98xx-objs += tfa_dsp.o
snd-soc-tfa98xx-objs += tfa_init.o
snd-soc-tfa98xx-objs += tfa_debug.o

obj-$(CONFIG_ZTE_NXP9890_SMART_PA_USE_QUIN)	+= snd-soc-tfa98xx.o
