
## lihaiyan@wind-mobi.com 20170331 begin
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/mach/

obj-y	:=  tl5601c.o 
### PSensor_Calibrator.o  LSensor_Calibrator.o

## lihaiyan@wind-mobi.com 20170331 end

