#hebiao@wind-mobi.com 20160324 modify begin
#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/misc/mediatek/magnetometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	:=  qmcX983.o
#hebiao@wind-mobi.com 20160324 modify end