# SPDX-License-Identifier: GPL-2.0

# Minimal System
obj-y += clk/
obj-y += pinctrl/
obj-y += uart/
obj-y += timer/

# Basic System
obj-y += dma/
obj-y += rtc/
obj-y += bus/
obj-y += dumpreg/
obj-y += watchdog/
obj-y += i2c/
obj-y += spi/
obj-y += ledc/
obj-y += pwm/
obj-y += ir-tx/
obj-y += ir-rx/
obj-y += gpadc/
obj-y += lradc/
obj-y += rtp/
obj-y += usb/
obj-y += iommu/
obj-y += emac/
obj-y += gmac/
obj-y += mbus/
obj-y += msgbox/
obj-y += hwspinlock/

# Power Management
obj-y += irqchip/
obj-y += standby/
obj-y += thermal/
obj-y += nvmem/
obj-y += pm_domain/
obj-y += power/
obj-y += cpufreq/
obj-y += devfreq/

# Input
obj-y += input/

# Storage
obj-y += mmc/

# Graphics
obj-y += video/
obj-y += g2d/
obj-y += di/
obj-y += vin/
obj-y += vfe/
obj-y += tvd/

# Multi-Media
obj-y += ve/

# Sound
obj-y += sound/

# Security
obj-y += smc/
obj-y += sid/
obj-y += secure_storage/
obj-y += drm_heap/

# Net
obj-y += net/

# Wireless
obj-y += bluetooth/

# Misc
obj-y += misc/

# Drm
obj-y += drm/

# Vendor hooks
obj-y += vendor_hooks/

# Crashdump
obj-y += crashdump/

# ATA
obj-y += ata/

# MTD
obj-y += mtd/

# Remoteproc
obj-y += remoteproc/

# Open source GPU
obj-y += gpu/panfrost/

KBUILD_CFLAGS	+= -Wno-implicit-fallthrough
KBUILD_CFLAGS	+= -Wno-array-parameter
KBUILD_CFLAGS	+= -Wno-misleading-indentation
KBUILD_CFLAGS	+= -Wno-implicit-function-declaration
KBUILD_CFLAGS	+= -Wno-int-conversion
KBUILD_CFLAGS	+= -Wno-tautological-compare
KBUILD_CFLAGS	+= -Wno-bool-operation
