# zhangkaiyuan@wind-mobi.com 20170926 
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += st7703_hd720_dsi_vdo_txd.o

# zhangkaiyuan@wind-mobi.com 20170926 end
