# zhangkaiyuan@wind-mobi.com 20161107 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += otm1289a_hsd_dsi_vdo_txd.o


# zhangkaiyuan@wind-mobi.com 20161107 end
