#modified hebiao@wind-mobi.com 201600822 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += ili7807d01_fhd_dsi_vdo_tianma.o

#modified hebiao@wind-mobi.com 201600822 end



