# SPDX-License-Identifier: GPL-2.0-or-later
#
# Allwinner audio codecs driver Makefile
#
# Copyright(c) 2022-2027 Allwinnertech Co., Ltd.

# Sunxi
snd-soc-ac107-objs := ac107.o

# Sunxi
obj-$(CONFIG_SND_SOC_AC107)	+= snd-soc-ac107.o
