# wangbing@wind-mobi.com 20170421 begin
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/mach/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/pa22a/

# wangbing@wind-mobi.com 20170426 begin
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/
# wangbing@wind-mobi.com 20170426 end
obj-y += txc_pa22a.o mtk_txc_alsprx.o
# wangbing@wind-mobi.com 20170421 end
