#yutao@wind-mobi.com 20160601 end
# In case the platform does NOT support this type of sensors
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y   += otg_chg_ctl.o

#yutao@wind-mobi.com 20160601 end