#modified qiangang@wind-mobi.com 20170207 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += s6d7aa6x01_hd720_dsi_vdo_hs.o

#modified qiangang@wind-mobi.com 20170207 end



