#hebiao@wind-mobi.com 2016112 begin
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	:=  n2dm.o
#hebiao@wind-mobi.com 2016112 end
