ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += zte_eeprom.o
obj-$(CONFIG_MSM_EEPROM) += common_eeprom.o
obj-$(CONFIG_S5K3L6_047_EEPROM) += s5k3l6_047_eeprom.o